### ISSUE TITLE
Improve usability of UI

### ISSUE THREAD

**Issue by thomasmomme** [GallVp/visualEEG#15]
- [x] Add Tooltip explanations to buttons
- [ ] Automatic UI buttons/fields "focus" for easy keyboard controls (RETURN & SPACE)

**Comment by GallVp** [comment]
Tooltips added. 57a69db

**Comment by GallVp** [comment]
Added focus functionality!! TAB to sequence through buttons and SPACE to hit the button. 52d5498

**Comment by GallVp** [comment]
Closing for now!!
