### ISSUE TITLE
save button is not working

### ISSUE THREAD

**Issue by usmanayubsh** [GallVp/visualEEG#18]
<kbd>save</kbd> button in tools menu of visualEEG gui is not working. Every other button in this menu seems to work fine. Here goes the error-log:

```
Undefined function 'export_fig' for input arguments of type
'char'.

Error in visualEEG>saveFigure_ClickedCallback (line 381)
export_fig(fullfile(strcat(handles.dSets.getDataSet.folderName,
'/Output Figures'),...

Error in gui_mainfcn (line 96)
        feval(varargin{:});

Error in visualEEG (line 51)
    gui_mainfcn(gui_State, varargin{:});

Error in
@(hObject,eventdata)visualEEG('saveFigure_ClickedCallback',hObject,eventdata,guidata(hObject))

 
Error while evaluating uipushtool ClickedCallback
```

And here go a few relevant details of my system:
OS: Linux (ubuntu 14.04 LTS)
MATLAB: R2013a

**Comment by GallVp** [comment]
Have you added the export_fig folder inside visualEEG folder to your path?

**Comment by usmanayubsh** [comment]
Yes I have. It didn't solve the problem.

**Comment by GallVp** [comment]
make a test plot like(`plot([0:0.01:3], sin([0:0.01:3]))`)in matlab. Then do an `export_fig test.pdf` in the command window!!
If that does not work!! Then there is something wrong with export_fig library on ubuntu!! Otherwise its something wrong with visualEEG!!

**Comment by usmanayubsh** [comment]
```
>> plot([0:0.01:3], sin([0:0.01:3]))
>> export_fig test.pdf
```
```
Undefined function 'export_fig' for input arguments of type
'char'.
```

**Comment by GallVp** [comment]
Yeah!! It makes sense now!! We need to figure out why export_fig is not working on ubuntu!!

**Comment by GallVp** [comment]
A better solution:

Matlab has built-in functions to save figures, although they don't generate same quality of graphics. So, following things can be done here:

1. Check if export_fig is working. 
2. If yes, save the figure and notify success with a dialog box.
3. If no, use matlab's built-in function to save the figure and notify success!!

**Comment by usmanayubsh** [comment]
I have found the source of problem. My `export_fig` and `FastICA` folders were empty because instead of using `git clone --recursive`, I used `git clone` to clone this repository. 
I think, this needs to be very clearly mentioned in the README of this project. Issue resolved, now I am going to close this issue. Thanks alot for your time.

**Comment by GallVp** [comment]
Improved save button functionality as per earlier comment. Now, if export_fig lib is not working, matlab's built-in funcs will be used to export graphics. Also, success and failure will be notified via dialogs. Ofcourse, the graphic quality of matlab's built-in funcs is lower than export_fig!!

**Comment by usmanayubsh** [comment]
Works like a charm! Thanks @GallVp.
![screenshot from 2016-07-15 21 20 10](https://cloud.githubusercontent.com/assets/8685049/16881850/7827e77a-4ad5-11e6-869a-7edf096cb19f.png)
